### ISSUE TITLE
t/get-unsized.t hangs on MacOS

### ISSUE THREAD

**Issue by zoffixznet** [raku-community-modules/LWP-Simple#28]
So far, I've seen two reports on IRC channel of MacOS users getting the [new t/get-unsized.t test](https://github.com/perl6/perl6-lwp-simple/blob/master/t/get-unsized.t) file to hang while installing Rakudo Star.

I don't have a MacOS, so I can't test/debug it. I've [temporarily fudged the test file on MacOS](https://github.com/perl6/perl6-lwp-simple/commit/3e34aae1f54052210a97baa0ff69a9912b483acf) (and https://github.com/perl6/perl6-lwp-simple/commit/f1257d6d75)

**Comment by enheh** [comment]
I'm seeing this problem on OS X 10.6.8.

I've added print statements before every line in the file to see where it hangs, and this is what I see:

> /usr/local/perl6.2018_04/bin/moar --execname=/usr/local/perl6.2018_04/bin/perl6-m --libpath=/usr/local/perl6.2018_04/share/nqp/lib --libpath=/usr/local/perl6.2018_04/share/nqp/lib --libpath=/usr/local/perl6.2018_04/share/perl6/lib --libpath=/usr/local/perl6.2018_04/share/perl6/runtime --libpath=/Users/enheh/builds/rakudo-star-2018.04/modules/perl6-lwp-simple /usr/local/perl6.2018_04/share/perl6/runtime/perl6.moarvm t/get-unsized.t
1..1
About to create new channel
About to start new thread
Main thread: about to call receive
Inside thread: about to start server

**Comment by JJ** [comment]
I don't really see a point in the test, and why it's stalling has nothing to do with actually testing a feature. What it's doing is creating a simple server, and then making a localhost  `get` request on that server. We could simply eliminate that test without decreasing the coverage. Anyway, I'm testing it on the latest MacOSx version (and Raku) to see if it still happens.
