### ISSUE TITLE
basic-auth.t dependency on www.software-path.com failing

### ISSUE THREAD

**Issue by dwarring** [raku-community-modules/LWP-Simple#51]
The host name is currently unknown. I'm getting:
```
avid@box:~/git/LWP-Simple$ prove6 -I. t/basic-auth.t 
t/basic-auth.t ..1/9Failed to resolve host name 'www.software-path.com' with family 0.
Error: Name or service not known
  in method make_request at /home/david/git/LWP-Simple/lib/LWP/Simple.rakumod (LWP::Simple) line 267
  in method request_shell at /home/david/git/LWP-Simple/lib/LWP/Simple.rakumod (LWP::Simple) line 103
  in method get at /home/david/git/LWP-Simple/lib/LWP/Simple.rakumod (LWP::Simple) line 47
  in block <unit> at t/basic-auth.t line 38

# You planned 9 tests, but ran 8
t/basic-auth.t .. Dubious, test returned 255
All 9 subtests passed 
```

**Comment by dwarring** [comment]
Seems also that `http://w3c.org` has started redirecting to `https`, which has required a fix to `get-w3-latin1-utf8.t`.

**Comment by dwarring** [comment]
tried a zef upload (first time for an `auth:raku-commiity-modules`). Does seemed to have indexed. Attempted release was `1.09`. Still at `1.08`.

**Comment by dwarring** [comment]
Is anyone able to release this module?

**Comment by dwarring** [comment]
I have changed the auth to `zef:dwarring` and released the module.

**Comment by lizmat** [comment]
Sorry, I meant to look at this:  `auth:raku-commiity-modules` is wrong, the "auth" should have been `zef:raku-community-modules`.

**Comment by dwarring** [comment]
Ah, I missed that it was a typo.
